### ISSUE TITLE
Website Grammatical Mistake

### ISSUE THREAD

**Issue by PikAsriel** [leomtz/apmowebsite#2]
In https://apmo-official.org/regulations, "The APMO is **be** held in the afternoon of the second Monday of March for participating countries in the North and South Americas, and in the morning of the second Tuesday of March for participating countries **on** the Western Pacific and in Asia." → "The APMO is held in the afternoon of the second Monday of March for participating countries in the North and South Americas, and in the morning of the second Tuesday of March for participating countries **in** the Western Pacific and in Asia."

**Comment by leomtz** [comment]
Corrected, thanks!
