### ISSUE TITLE
Asian Pacific Mathematics Olympiad (2004) Solution

### ISSUE THREAD

**Issue by PikAsriel** [leomtz/apmowebsite#3]
https://docs.google.com/document/d/1mZkcvGOeS86qkpMB0YWMsy3YpU8m7Zm0dq-suHZ-_dI/edit?usp=sharing

Thank you.

**Comment by PikAsriel** [comment]
I rewrite it in LaTeX: https://github.com/PikAsriel/pikasriel.github.io/tree/main/APMO)/THE_2004_ASIAN_PACIFIC_MATHEMATICAL_OLYMPIAD_SOLUTION.pdf

**Comment by leomtz** [comment]
We added the solutions with some minor corrections, thanks!
